### PR TITLE
the effect of grid_ao sparsification on energy error

### PR DESCRIPTION
**Pull request by blazejba**
Addresses [#61](https://github.com/graphcore-research/pyscf-ipu/issues/61)

### CODE REVIEW

**Comment by blazejba** [comment]
# Sparsity
Screenshot 2023-09-07 at 15 41 57

# Errors
Screenshot 2023-09-07 at 15 41 04
Screenshot 2023-09-07 at 15 41 24
Screenshot 2023-09-07 at 15 41 36
Screenshot 2023-09-07 at 15 41 46

**Comment by AlexanderMath** [comment]
Beautiful. Only comment: Would it take too long to run for 10,20,40,80 carbons?

**Comment by blazejba** [comment]
So far the sparsity results for methane, benzene and 4,6,8,16,32,64 c atoms look promising

output

However the errors grow considerably for larger sets

err_c_32
hlerror_c_32

**Comment by blazejba** [comment]
`python nanoDFT.py --mol_str c_64 --ao_threshold_exp -10` kills the machine, 32 carbon atoms is highest I was able to run

**Comment by AlexanderMath** [comment]
Neat, happy to see we add only few lines to `nanoDFT.py`. 

**Bug/error** (not caught by tests for some reason). The default value `opts.ao_threshold_exp=0` means 
```
grid_AO[np.abs(grid_AO) < 10**(opts.ao_threshold_exp)] = grid_AO[np.abs(grid_AO) < 1] = 0
```
I think all values in `grid_AO` satisfies `grid_AO<1` so the change means default run would not agree with PySCF. 

**Solution:** I'd prefer if we (similar to opts.threshold) instead do `grid_AO[np.abs(grid_AO)<opts.ao_threadshold]`. Note the user from command-line can still write `--opts.ao_threshold 1e-7`. It might also be nice to change `opts.threshold` to `opts.eri_threshold`.

**Comment by blazejba** [comment]
Nice, addressed your comments and expanded the plots with results for threshold values 1e-3 

---- 

energy_err

hl_err


sparse

**Review by AlexanderMath — APPROVED** [review]
lgtm

**Pull request merged**
